<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TipoTurno;

class TipoTurnoSeeder extends Seeder
{
    public function run(): void
    {
        $tipos = [
            [
                'codigo'         => 'M',
                'nombre'         => 'Mañana',
                'hora_inicio'    => '07:00:00',
                'hora_fin'       => '13:00:00',
                'horas_diurnas'  => 6.0,
                'horas_nocturnas'=> 0.0,
                'horas_total'    => 6.0,
                'color_hex'      => '#2196F3',
                'color_clase'    => 'badge-M',
                'es_ausencia'    => false,
                'cubre_manana'   => true,
                'cubre_tarde'    => false,
                'cubre_noche'    => false,
                'solo_finde'     => false,
            ],
            [
                'codigo'         => 'T',
                'nombre'         => 'Tarde',
                'hora_inicio'    => '13:00:00',
                'hora_fin'       => '19:00:00',
                'horas_diurnas'  => 6.0,
                'horas_nocturnas'=> 0.0,
                'horas_total'    => 6.0,
                'color_hex'      => '#4CAF50',
                'color_clase'    => 'badge-T',
                'es_ausencia'    => false,
                'cubre_manana'   => false,
                'cubre_tarde'    => true,
                'cubre_noche'    => false,
                'solo_finde'     => false,
            ],
            [
                'codigo'         => 'MT',
                'nombre'         => 'Mañana-Tarde',
                'hora_inicio'    => '07:00:00',
                'hora_fin'       => '19:00:00',
                'horas_diurnas'  => 12.0,
                'horas_nocturnas'=> 0.0,
                'horas_total'    => 12.0,
                'color_hex'      => '#FF9800',
                'color_clase'    => 'badge-MT',
                'es_ausencia'    => false,
                'cubre_manana'   => true,
                'cubre_tarde'    => true,
                'cubre_noche'    => false,
                'solo_finde'     => false,
            ],
            [
                'codigo'         => 'N',
                'nombre'         => 'Noche',
                'hora_inicio'    => '19:00:00',
                'hora_fin'       => '07:00:00',
                'horas_diurnas'  => 0.0,
                'horas_nocturnas'=> 12.0,
                'horas_total'    => 12.0,
                'color_hex'      => '#673AB7',
                'color_clase'    => 'badge-N',
                'es_ausencia'    => false,
                'cubre_manana'   => false,
                'cubre_tarde'    => false,
                'cubre_noche'    => true,
                'solo_finde'     => false,
            ],
            [
                'codigo'         => 'MTN',
                'nombre'         => 'Mañana-Tarde-Noche',
                'hora_inicio'    => '07:00:00',
                'hora_fin'       => '07:00:00',   // día siguiente
                'horas_diurnas'  => 12.0,
                'horas_nocturnas'=> 12.0,
                'horas_total'    => 24.0,
                'color_hex'      => '#880E4F',
                'color_clase'    => 'badge-MTN',
                'es_ausencia'    => false,
                'cubre_manana'   => true,
                'cubre_tarde'    => true,
                'cubre_noche'    => true,
                'solo_finde'     => true,         // solo sábado y domingo
            ],
            [
                'codigo'         => 'MN',
                'nombre'         => 'Mañana-Noche',
                'hora_inicio'    => '07:00:00',
                'hora_fin'       => '07:00:00',
                'horas_diurnas'  => 6.0,
                'horas_nocturnas'=> 12.0,
                'horas_total'    => 18.0,
                'color_hex'      => '#E91E63',
                'color_clase'    => 'badge-MN',
                'es_ausencia'    => false,
                'cubre_manana'   => true,
                'cubre_tarde'    => false,
                'cubre_noche'    => true,
                'solo_finde'     => false,
            ],
            [
                'codigo'         => 'VAC',
                'nombre'         => 'Vacaciones',
                'hora_inicio'    => null,
                'hora_fin'       => null,
                'horas_diurnas'  => 0.0,
                'horas_nocturnas'=> 0.0,
                'horas_total'    => 0.0,
                'color_hex'      => '#00BCD4',
                'color_clase'    => 'badge-VAC',
                'es_ausencia'    => true,
                'cubre_manana'   => false,
                'cubre_tarde'    => false,
                'cubre_noche'    => false,
                'solo_finde'     => false,
            ],
            [
                'codigo'         => 'PER',
                'nombre'         => 'Permiso',
                'hora_inicio'    => null,
                'hora_fin'       => null,
                'horas_diurnas'  => 0.0,
                'horas_nocturnas'=> 0.0,
                'horas_total'    => 0.0,
                'color_hex'      => '#FFC107',
                'color_clase'    => 'badge-PER',
                'es_ausencia'    => true,
                'cubre_manana'   => false,
                'cubre_tarde'    => false,
                'cubre_noche'    => false,
                'solo_finde'     => false,
            ],
            [
                'codigo'         => 'INC',
                'nombre'         => 'Incapacidad',
                'hora_inicio'    => null,
                'hora_fin'       => null,
                'horas_diurnas'  => 0.0,
                'horas_nocturnas'=> 0.0,
                'horas_total'    => 0.0,
                'color_hex'      => '#F44336',
                'color_clase'    => 'badge-INC',
                'es_ausencia'    => true,
                'cubre_manana'   => false,
                'cubre_tarde'    => false,
                'cubre_noche'    => false,
                'solo_finde'     => false,
            ],
            [
                'codigo'         => 'LIBRE',
                'nombre'         => 'Libre',
                'hora_inicio'    => null,
                'hora_fin'       => null,
                'horas_diurnas'  => 0.0,
                'horas_nocturnas'=> 0.0,
                'horas_total'    => 0.0,
                'color_hex'      => '#9E9E9E',
                'color_clase'    => 'badge-LIBRE',
                'es_ausencia'    => false,
                'cubre_manana'   => false,
                'cubre_tarde'    => false,
                'cubre_noche'    => false,
                'solo_finde'     => false,
            ],
        ];

        foreach ($tipos as $tipo) {
            TipoTurno::updateOrCreate(['codigo' => $tipo['codigo']], $tipo);
        }
    }
}
